In [1]:
import pandas as pd

In [2]:
fangraphs = pd.read_csv("/Users/Jaron/Desktop/INST414 Files/Module Assignments/fangraphs_season_level.csv")

In [3]:
fangraphs.head()

,PlayerId,MLBAMID,Name,NameASCII,Throws,Season,Age,Team,Role,G,...,Pit_plus_FC,Stf_plus_FS,Loc_plus_FS,Pit_plus_FS,Stf_plus_FO,Loc_plus_FO,Pit_plus_FO,Stuff_plus,Location_plus,Pitching_plus
0,18,491703,NeftalÃ­ Feliz,Neftali Feliz,R,2021,33,- - -,RP,5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,104.316418,95.123881,95.873134
1,1157,488984,Tommy Hunter,Tommy Hunter,R,2021,34,NYM,RP,3,...,103.100000,NaN,NaN,NaN,NaN,NaN,NaN,86.285556,94.884444,95.112222
2,1159,461865,Andrew Romine,Andrew Romine,R,2021,35,CHC,RP,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,43.925000,108.425000,99.200000
3,1246,456713,Matt Bush,Matt Bush,R,2021,35,TEX,RP,4,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,124.852174,98.340580,102.611594
4,1247,493603,Adam Ottavino,Adam Ottavino,R,2021,35,BOS,RP,69,...,66.583333,NaN,NaN,NaN,NaN,NaN,NaN,116.269527,94.625394,102.238617

In [310]:
data = fangraphs[fangraphs['Season'] == 2023]

data = data[data['IP'] >= 25]

data = data[['NameASCII', 'K_pct', 'BB_pct', 'H_per_9', 'xFIP', 'OSwing_pct', 'CSW_pct', 'HardHit_pct', 'Stuff_plus', 'Pitching_plus']]

data = data.set_index('NameASCII')

data.head()

,K_pct,BB_pct,H_per_9,xFIP,OSwing_pct,CSW_pct,HardHit_pct,Stuff_plus,Pitching_plus
NameASCII,,,,,,,,,
Adam Ottavino,0.2375,0.1111,6.713510,4.331163,0.2967,0.3035,0.4074,100.091211,95.718750
Kenley Jansen,0.2766,0.0904,8.059696,4.608799,0.3508,0.2859,0.3590,119.842580,111.271845
Jesse Chavez,0.2667,0.0815,6.958770,3.308249,0.2883,0.3247,0.3372,101.248069,96.436293
Ryan Brasier,0.2353,0.0798,6.335192,4.035840,0.3484,0.2608,0.4250,106.076598,106.066727
Huascar Brazoban,0.2529,0.1206,8.130677,4.097100,0.3631,0.2970,0.2803,90.740909,98.185375

In [311]:
len(data)

519

In [315]:
data_norm = data.divide(data.sum(axis=1), axis=0)
data_norm.head(10)

,K_pct,BB_pct,H_per_9,xFIP,OSwing_pct,CSW_pct,HardHit_pct,Stuff_plus,Pitching_plus
NameASCII,,,,,,,,,
Adam Ottavino,0.001141,0.000534,0.032244,0.020802,0.001425,0.001458,0.001957,0.480720,0.459720
Kenley Jansen,0.001128,0.000369,0.032877,0.018800,0.001431,0.001166,0.001464,0.488863,0.453901
Jesse Chavez,0.001275,0.000389,0.033256,0.015810,0.001378,0.001552,0.001611,0.483862,0.460867
Ryan Brasier,0.001051,0.000356,0.028299,0.018028,0.001556,0.001165,0.001898,0.473845,0.473801
Huascar Brazoban,0.001249,0.000596,0.040158,0.020236,0.001793,0.001467,0.001384,0.448174,0.484943
Trevor May,0.000946,0.000686,0.032720,0.027573,0.001421,0.001377,0.001749,0.457627,0.475900
Jose Cisnero,0.001202,0.000429,0.043804,0.019233,0.001393,0.001248,0.002031,0.484122,0.446537
Craig Kimbrel,0.001352,0.000403,0.022947,0.014294,0.001188,0.001239,0.001868,0.500564,0.456146
Luis Garcia,0.000879,0.000398,0.039425,0.017774,0.001367,0.001088,0.001565,0.487358,0.450145
Ryan Pressly,0.000970,0.000210,0.026124,0.011016,0.001309,0.001117,0.001528,0.546541,0.411187

In [316]:
from scipy.sparse import lil_matrix
import scipy.spatial.distance

# Target Player 1: Logan Webb

In [317]:
target_player1 = ('Logan Webb') 

target_player1

'Logan Webb'

In [318]:
target_player1_stats = data_norm.loc[target_player1]

target_player1_stats

K_pct            0.001041
BB_pct           0.000167
H_per_9          0.038212
xFIP             0.013477
OSwing_pct       0.001580
CSW_pct          0.001338
HardHit_pct      0.002075
Stuff_plus       0.473015
Pitching_plus    0.469094
Name: Logan Webb, dtype: float64

In [319]:
distances = scipy.spatial.distance.cdist(data_norm, [target_player1_stats], metric="euclidean")[:,0]

In [320]:
query_distances = list(zip(data_norm.index, distances))

#query_distances.sort(key=lambda x: x[1])

#query_distances

comps = pd.DataFrame(query_distances, columns = ["Pitcher", "Distance"])

comps = comps.sort_values(by = ['Distance']).dropna()

comps.head(11)

            Pitcher  Distance
356      Logan Webb  0.000000
240     Gabe Speier  0.003718
328   Kevin Gausman  0.004187
78      Joe Jimenez  0.004351
488   Jesus Luzardo  0.004481
353    Mitch Keller  0.004510
377    Aaron Civale  0.005740
103  Adbert Alzolay  0.006121
312       Seth Lugo  0.006275
205      Matt Moore  0.006338
32     John Brebbia  0.006517

In [321]:
comps.tail(11)

             Pitcher  Distance
249    Andrew Suarez  0.098134
201  Daniel Palencia  0.102689
206     Jake Diekman  0.103100
475    Kyle Freeland  0.103117
221      Hoby Milner  0.103678
109     Ryan Helsley  0.103704
511    Jared Shuster  0.105953
302     Jacob deGrom  0.110508
513    Cody Bradford  0.116601
185      Abner Uribe  0.116786
309   Kyle Hendricks  0.147692

# Target Player 2: Cole Ragans

In [334]:
target_player2 = ('Kyle Bradish') 

target_player2

'Kyle Bradish'

In [335]:
target_player2_stats = data_norm.loc[target_player2]

target_player2_stats

K_pct            0.001032
BB_pct           0.000270
H_per_9          0.029019
xFIP             0.014547
OSwing_pct       0.001256
CSW_pct          0.001201
HardHit_pct      0.001727
Stuff_plus       0.518411
Pitching_plus    0.432538
Name: Kyle Bradish, dtype: float64

In [336]:
distances = scipy.spatial.distance.cdist(data_norm, [target_player2_stats], metric="euclidean")[:,0]

In [337]:
query_distances = list(zip(data_norm.index, distances))

#query_distances.sort(key=lambda x: x[1])

#query_distances

comps = pd.DataFrame(query_distances, columns = ["Pitcher", "Distance"])

comps = comps.sort_values(by = ['Distance']).dropna()

comps.head(11)

               Pitcher  Distance
417       Kyle Bradish  0.000000
372      Corbin Burnes  0.002958
81       Jordan Romano  0.003556
15     David Robertson  0.003857
50         Paul Sewald  0.004018
82      Reynaldo Lopez  0.005566
26          Jason Adam  0.006437
204  Shintaro Fujinami  0.008167
80         Ryne Stanek  0.008545
46         Clay Holmes  0.008656
155        Jhoan Duran  0.008738

# Target Player 3: Matt Brash

In [382]:
target_player3 = ('Devin Williams') 

target_player3

'Devin Williams'

In [383]:
target_player3_stats = data_norm.loc[target_player3]

target_player3_stats

K_pct            0.001631
BB_pct           0.000525
H_per_9          0.017277
xFIP             0.012070
OSwing_pct       0.001481
CSW_pct          0.001427
HardHit_pct      0.001281
Stuff_plus       0.493715
Pitching_plus    0.470592
Name: Devin Williams, dtype: float64

In [384]:
distances = scipy.spatial.distance.cdist(data_norm, [target_player3_stats], metric="euclidean")[:,0]

In [385]:
query_distances = list(zip(data_norm.index, distances))

comps = pd.DataFrame(query_distances, columns = ["Pitcher", "Distance"])

comps = comps.sort_values(by = ['Distance']).dropna()

comps.head(11)

              Pitcher  Distance
79     Devin Williams  0.000000
227        Josh Hader  0.008342
342  Brandon Woodruff  0.009697
134      Kevin Ginkel  0.013190
246     Jose Alvarado  0.014578
463       Blake Snell  0.015000
17          Joe Kelly  0.015103
203     Robert Suarez  0.015867
420    Drew Rasmussen  0.016202
88      Ryan Thompson  0.016404
58       Emilio Pagan  0.016706